### PR TITLE
TravisCI integration

### PR DESCRIPTION
**Pull request by a-one-d-one**
integration of TravisCI as per issue opened.

### CODE REVIEW

**Comment by haoRchen** [comment]
thanks!

**Comment by a-one-d-one** [comment]
Anytime!!

**Comment by SeanPrashad** [comment]
Has Travis been enabled for this repo? If so, add the badge that shows if it's building successfully into your README.md

**Comment by haoRchen** [comment]
@a-one-d-one  Please send a PR for a badge in README that links Travis. Thank you

**Pull request merged**
